DROP TABLE IF EXISTS `ir`;
CREATE TABLE IF NOT EXISTS `ir` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `IP` varchar(16) COLLATE utf8mb4_persian_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2705 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;
